# Generated by Django 5.2.7 on 2025-10-24 01:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habitacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(db_index=True, max_length=10, unique=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("D", "Disponible"),
                            ("A", "Asignada a empresa"),
                            ("M", "En mantenimiento"),
                            ("O", "Ocupada"),
                            ("L", "Para Limpieza"),
                        ],
                        default="D",
                        help_text="Estado de disponibilidad de la habitación [cite: 16]",
                        max_length=1,
                    ),
                ),
                (
                    "tipo_cama",
                    models.CharField(
                        help_text="Datos propios de la habitación [cite: 20]",
                        max_length=100,
                    ),
                ),
                (
                    "accesorios",
                    models.TextField(
                        blank=True, help_text="Accesorios de la habitación [cite: 20]"
                    ),
                ),
                (
                    "precio",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Precio de la habitación [cite: 20]",
                        max_digits=10,
                    ),
                ),
            ],
            options={
                "ordering": ["numero"],
            },
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "razon_social",
                    models.CharField(
                        help_text="Datos de la empresa [cite: 13]",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "rut",
                    models.CharField(
                        db_index=True,
                        max_length=12,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{7,8}-[0-9kK]$",
                                "Formato RUT inválido. Ej: 12345678-9",
                            )
                        ],
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Usuario de la empresa para iniciar sesión",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cliente_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["razon_social"],
            },
        ),
        migrations.CreateModel(
            name="OrdenDeCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo_orden",
                    models.CharField(
                        db_index=True,
                        help_text="Código de la orden de compra",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("fecha_emision", models.DateField(auto_now_add=True)),
                (
                    "lista_huespedes_excel",
                    models.FileField(
                        blank=True,
                        help_text="Permite registrar la lista de huéspedes por planilla [cite: 38]",
                        null=True,
                        upload_to="listas_excel/",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        help_text="Cliente que emite la orden",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ordenes",
                        to="hostal.cliente",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_emision"],
            },
        ),
        migrations.CreateModel(
            name="Huesped",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rut",
                    models.CharField(
                        db_index=True,
                        max_length=12,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{7,8}-[0-9kK]$",
                                "Formato RUT inválido. Ej: 12345678-9",
                            )
                        ],
                    ),
                ),
                ("nombre_completo", models.CharField(max_length=255)),
                (
                    "empresa",
                    models.ForeignKey(
                        help_text="Empresa de procedencia [cite: 27]",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="huespedes",
                        to="hostal.cliente",
                    ),
                ),
                (
                    "habitacion",
                    models.ForeignKey(
                        blank=True,
                        help_text="Habitación asignada [cite: 28, 37]",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ocupantes",
                        to="hostal.habitacion",
                    ),
                ),
                (
                    "orden_de_compra_asociada",
                    models.ForeignKey(
                        blank=True,
                        help_text="Orden de compra que valida su estadía",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hostal.ordendecompra",
                    ),
                ),
            ],
            options={
                "ordering": ["nombre_completo"],
            },
        ),
        migrations.AddIndex(
            model_name="cliente",
            index=models.Index(fields=["rut"], name="hostal_clie_rut_6a5bb1_idx"),
        ),
        migrations.AddIndex(
            model_name="ordendecompra",
            index=models.Index(
                fields=["codigo_orden"], name="hostal_orde_codigo__39e6cc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="huesped",
            index=models.Index(fields=["rut"], name="hostal_hues_rut_b8152b_idx"),
        ),
    ]
