# Generated by Django 5.2.7 on 2025-10-27 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hostal", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="razon_social",
            field=models.CharField(
                help_text="Datos de la empresa.", max_length=255, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="habitacion",
            name="accesorios",
            field=models.TextField(blank=True, help_text="Accesorios de la habitación"),
        ),
        migrations.AlterField(
            model_name="habitacion",
            name="estado",
            field=models.CharField(
                choices=[
                    ("D", "Disponible"),
                    ("A", "Asignada a empresa"),
                    ("M", "En mantenimiento"),
                    ("O", "Ocupada"),
                    ("L", "Para Limpieza"),
                ],
                default="D",
                help_text="Estado de disponibilidad de la habitación",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="habitacion",
            name="precio",
            field=models.DecimalField(
                decimal_places=2, help_text="Precio de la habitación", max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="habitacion",
            name="tipo_cama",
            field=models.CharField(
                help_text="Datos propios de la habitación", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="huesped",
            name="empresa",
            field=models.ForeignKey(
                help_text="Empresa de procedencia.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="huespedes",
                to="hostal.cliente",
            ),
        ),
        migrations.AlterField(
            model_name="huesped",
            name="habitacion",
            field=models.ForeignKey(
                blank=True,
                help_text="Habitación asignada.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ocupantes",
                to="hostal.habitacion",
            ),
        ),
        migrations.AlterField(
            model_name="ordendecompra",
            name="lista_huespedes_excel",
            field=models.FileField(
                blank=True,
                help_text="Permite registrar la lista de huéspedes por planilla.",
                null=True,
                upload_to="listas_excel/",
            ),
        ),
    ]
