# Generated by Django 5.2.7 on 2025-11-15 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hostal", "0003_plato_minutadia"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MinutaDia",
        ),
        migrations.DeleteModel(
            name="Plato",
        ),
    ]
