# Generated by Django 5.2.8 on 2025-11-29 05:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hostal", "0004_delete_minutadia_delete_plato"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habitacion",
            name="precio",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Precio de la habitación",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
