# Generated by Django 5.2.8 on 2025-11-29 06:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hostal", "0005_alter_habitacion_precio"),
    ]

    operations = [
        migrations.AddField(
            model_name="habitacion",
            name="capacidad",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Capacidad máxima de personas",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
