# Generated by Django 5.2.8 on 2025-11-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hostal", "0006_habitacion_capacidad"),
    ]

    operations = [
        migrations.AddField(
            model_name="habitacion",
            name="bloqueada_ingreso",
            field=models.BooleanField(
                default=False,
                help_text="Si está activo, impide agregar nuevos huéspedes aunque haya capacidad.",
                verbose_name="Bloqueo de Ingreso",
            ),
        ),
    ]
