# Generated by Django 5.2.7 on 2025-12-02 00:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hostal", "0007_habitacion_bloqueada_ingreso"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habitacion",
            name="precio",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Precio de la habitación",
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(
                        0,
                        message="El precio no puede ser negativo. Ingrese un valor mayor o igual a 0.",
                    )
                ],
            ),
        ),
    ]
