# Generated by Django 5.2.7 on 2025-10-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200, unique=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("entrada", "Entrada"),
                            ("fondo", "Plato de Fondo"),
                            ("postre", "Postre"),
                            ("bebida", "Bebida"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, help_text="Ingredientes o detalles"),
                ),
            ],
            options={
                "ordering": ["tipo", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="MinutaDia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha",
                    models.DateField(
                        help_text="Fecha para la que aplica este menú", unique=True
                    ),
                ),
                (
                    "platos",
                    models.ManyToManyField(
                        help_text="Seleccione los platos disponibles para este día",
                        related_name="minutas",
                        to="comedor.plato",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha"],
            },
        ),
    ]
