# Generated by Django 5.2.7 on 2025-11-15 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FamiliaProducto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        help_text="Código de 3 dígitos", max_length=3, unique=True
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_proveedor",
                    models.CharField(
                        help_text="ID de 3 dígitos", max_length=3, unique=True
                    ),
                ),
                ("razon_social", models.CharField(max_length=255, unique=True)),
                ("rut", models.CharField(max_length=12, unique=True)),
                (
                    "contacto",
                    models.CharField(help_text="Nombre del contacto", max_length=255),
                ),
                ("telefono", models.CharField(max_length=20)),
                ("rubro", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "Proveedores",
            },
        ),
        migrations.CreateModel(
            name="OrdenPedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_emision", models.DateTimeField(auto_now_add=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("P", "Pendiente"),
                            ("R", "Recibido"),
                            ("C", "Cancelado"),
                        ],
                        default="P",
                        max_length=1,
                    ),
                ),
                (
                    "solicitante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="administracion.proveedor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                (
                    "sku_secuencial",
                    models.CharField(help_text="Secuencial de 3 dígitos", max_length=3),
                ),
                ("precio_costo", models.DecimalField(decimal_places=2, max_digits=10)),
                ("stock_actual", models.IntegerField(default=0)),
                (
                    "familia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="administracion.familiaproducto",
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="productos",
                        to="administracion.proveedor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DetallePedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField()),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "orden",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="administracion.ordenpedido",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="administracion.producto",
                    ),
                ),
            ],
        ),
    ]
