# Generated by Django 5.2.7 on 2025-11-15 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administracion", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Empleado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rut",
                    models.CharField(
                        help_text="RUT del empleado", max_length=12, unique=True
                    ),
                ),
                ("telefono", models.CharField(blank=True, max_length=20)),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Administrador General"),
                            ("RECEPCION", "Recepcionista"),
                            ("COCINA", "Encargado de Cocina"),
                            ("BODEGA", "Encargado de Bodega"),
                        ],
                        default="RECEPCION",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="empleado_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
