# Generated by Django 5.2.8 on 2025-11-28 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administracion", "0002_empleado"),
        ("hostal", "0004_delete_minutadia_delete_plato"),
    ]

    operations = [
        migrations.CreateModel(
            name="Factura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_emision", models.DateTimeField(auto_now_add=True)),
                ("fecha_vencimiento", models.DateField(blank=True, null=True)),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=0,
                        help_text="Monto total en pesos",
                        max_digits=12,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("PAGADA", "Pagada"),
                            ("ANULADA", "Anulada"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                    ),
                ),
                (
                    "archivo",
                    models.FileField(blank=True, null=True, upload_to="facturas/"),
                ),
                ("observaciones", models.TextField(blank=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="facturas",
                        to="hostal.cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Factura",
                "verbose_name_plural": "Facturas",
                "ordering": ["-fecha_emision"],
            },
        ),
    ]
